name: murmuration
description: A powerful and flexible AI agent framework for building intelligent applications with support for multiple LLM providers (OpenAI, Anthropic, Google) and tool chaining.
version: 3.1.1
homepage: https://github.com/AgnivaMaiti/murmuration
repository: https://github.com/AgnivaMaiti/murmuration.git
documentation: https://github.com/AgnivaMaiti/murmuration#readme
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependency_overrides:
  # Ensure all dependencies use null-safe versions
  collection: ^1.18.0
  meta: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  google_generative_ai: ^0.2.0  # For Google Gemini integration
  http: ^1.1.0                  # For HTTP requests
  shared_preferences: ^2.2.0    # For local storage
  synchronized: ^3.1.0          # For thread safety
  path_provider: ^2.1.0         # For file system access
  intl: ^0.19.0                # For internationalization
  json_annotation: ^4.8.1       # For JSON serialization
  anthropic_sdk_dart: ^0.2.2     # For Anthropic Claude integration
  logger: ^2.0.0               # For structured logging
  uuid: ^4.0.0                 # For generating unique IDs
  meta: ^1.10.0                # For annotations
  collection: ^1.18.0          # For collection utilities
  flutter_dotenv: ^5.1.0        # For environment variable loading in examples
  path: ^1.8.3                 # For path manipulation
  crypto: ^3.0.3               # For cryptographic hashing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0         # For linting
  test: ^1.24.0                 # For testing
  build_runner: ^2.4.6          # For code generation
  json_serializable: ^6.7.1     # For JSON serialization
  mockito: ^5.4.2               # For mocking in tests
  dash_chat_2: ^0.0.21          # For chat UI components
  pedantic: ^1.11.1             # For additional lint rules
  very_good_analysis: ^5.1.0    # For additional analysis options

flutter:
  uses-material-design: true
  assets:
    - assets/

# Platform-specific settings
web:
  # Add web-specific settings here
