name: murmuration
description: "A framework for multi-agent orchestration in Dart (Flutter)."
version: 1.0.1
homepage: https://github.com/AgnivaMaiti/murmuration

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
